---
title: "Conclusion"
output: html_document
---

# 4 / Conclusion
```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/Setup.R"))
```
The work environment in which an employee evolves has an impact on his/her mental health. This is true in all the countries studied, although there are differences between regions which are probably related to another domain (politics, access to health care, etc.).

Regarding our study on Covid, we were able to see that the Covid crisis had an impact on the mental health of a country's population. Indeed, we proved that there was a link between the rate of teleworking of a country and the consumption of antidepressants of its population. Countries with more teleworkers on average are also countries with higher consumption of antidepressants per day per 100 inhabitants. This was also the case in 2020 when Covid arrived. 
However, it doesn't prove that teleworkers use more antidepressants than other people. 
Indeed, the year of covid, teleworking increased a lot in many countries, leading us to the conclusion that antidepressant consumption has increased in part because of that and thus because of Covid.
 
We can also see from the study of the depression rate of the countries that Covid must have had an impact on it, since it increased significantly that year. However, we could not prove with certainty that the countries most affected by Covid were also the countries with the highest depression rates. 

To conclude, Covid has had an impact on the mental health of the countries' populations, but it is also about everything involved in this crisis that has impacted people's mental illness. Indeed, the increase in telecommuting is a consequence of Covid which is then linked to mental health. However, there are many other variables caused by Covid that have not been taken into account, such as isolation, physical health (due to covid) or loss of relatives etc., and it would have been interesting to observe these variables.


To highlight the link between all the research questions: 

It is not possible to explain 100% of the prevalence of mental health by focusing only on the economic conditions of a country. Our results manage to explain some causality between these prevalence evolutions, such as income inequality. 

To return to our initial question: Is it possible to admit a causal link between the mental health of an OECD country and the economic conditions and the working environment? The answer is that these factors are linked, but they are only a small part of a larger model. 

The covid also had a big impact as can be seen from the graph. However, the studies are still limited in this respect if they focus on variables such as teleworking. 

Finally, the results for public expenditure on health show that, as with the working environment, the values are mainly clustered around their locality. This implies that other dimensions are not taken into account in our model, such as culture, political system, and many others. 



### Limitations

Our project leads us to an interesting conclusion. Nevertheless, it has many limitations that we must be careful about regarding its accuracy and validity. 
We encountered a first problem concerning the lack of data, all our variables did not have data available for each year (2000 to 2017) and especially concerning the recent data and for the covid part. We were also confronted with certain biases in the precision and quantification of certain countries whose data seemed to be over or underestimated (ex: China with numbers of Covid-19 cases and deaths that seem to be underestimated). Moreover, our analysis of the problem focuses only on OECD countries. Thus, its conclusions are not applicable or representative to countries worldwide. Last but not least, we used the 'Mental Health' data as a whole, which also includes information about populations other than employees (e.g. children, non-working adults, etc.). All this without forgetting that the quantification of mental health and the disorders that make it up (depression, anxiety, etc.) are extremely complex. It is therefore difficult to reduce it only to the work environment.


### Future work

Some countries must have elements external to the work environment (policy, access to healthcare, etc.) which have an impact on it and therefore on the mental health of workers.
So, it would therefore be interesting to be able to analyze how a country or a region organizes its company so that workers have the best possible conditions.

It would have been interesting to observe what part of a country's population consumes the most antidepressants and whether it is indeed the working population. In this way, we could have shown that people who telework use antidepressants.
